on:
  push:
    branches:
    - main
    - release/*

jobs:
  deploy_to_marketplace:
    name: deploy to microsoft visualstudio marketplace
    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.5.1
      with:
        node-version: 16
    - name: Install Dependencies
      run: npm install
    - name: Install packaging extension
      run: npm i -g tfx-cli
    - name: Build extension
      run: tfx extension create --manifest-globs vss-extension.json --rev-version
